# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QMainWindow,QLabel
from PyQt5.QtGui import QImage, QPainter, QPen,QPixmap
from PyQt5.QtCore import Qt, QPoint
import sys
import io
from PIL import Image
class PaintWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.lastPoint = QPoint()
        self.endPoint = QPoint()
        self.drawing = False
        self.pix = QPixmap(600, 500)  # 你想要的 QPixmap 大小
        self.pix.fill(Qt.black)  # 填充白色背景

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.drawPixmap(0, 0, self.pix)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.drawing = True
            self.lastPoint = event.pos()

    def mouseMoveEvent(self, event):
        if event.buttons() & Qt.LeftButton & self.drawing:
            painter = QPainter(self.pix)
            painter.setPen(QPen(Qt.white, 12, Qt.SolidLine, Qt.RoundCap, Qt.RoundJoin))
            self.endPoint = event.pos()
            painter.drawLine(self.lastPoint, self.endPoint)
            self.lastPoint = self.endPoint
            self.update()

    def mouseReleaseEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.drawing = False
    def clear(self):
        self.pix.fill(Qt.black)
        self.update()  # 更新塗鴉板
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Load_Image = QtWidgets.QPushButton(self.centralwidget)
        self.Load_Image.setGeometry(QtCore.QRect(20, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semilight")
        self.Load_Image.setFont(font)
        self.Load_Image.setObjectName("Load_Image")
        self.Load_Video = QtWidgets.QPushButton(self.centralwidget)
        self.Load_Video.setGeometry(QtCore.QRect(20, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semilight")
        self.Load_Video.setFont(font)
        self.Load_Video.setObjectName("Load_Video")
        self.Background_Subtraction = QtWidgets.QGroupBox(self.centralwidget)
        self.Background_Subtraction.setGeometry(QtCore.QRect(200, 10, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semilight")
        self.Background_Subtraction.setFont(font)
        self.Background_Subtraction.setObjectName("Background_Subtraction")
        self.Background_Subtraction_button = QtWidgets.QPushButton(self.Background_Subtraction)
        self.Background_Subtraction_button.setGeometry(QtCore.QRect(20, 40, 161, 41))
        self.Background_Subtraction_button.setObjectName("Background_Subtraction_button")
        self.Optical_Flow = QtWidgets.QGroupBox(self.centralwidget)
        self.Optical_Flow.setGeometry(QtCore.QRect(200, 160, 201, 171))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semilight")
        self.Optical_Flow.setFont(font)
        self.Optical_Flow.setObjectName("Optical_Flow")
        self.Preprocessing = QtWidgets.QPushButton(self.Optical_Flow)
        self.Preprocessing.setGeometry(QtCore.QRect(20, 42, 151, 31))
        self.Preprocessing.setObjectName("Preprocessing")
        self.Video_tracking = QtWidgets.QPushButton(self.Optical_Flow)
        self.Video_tracking.setGeometry(QtCore.QRect(20, 110, 151, 31))
        self.Video_tracking.setObjectName("Video_tracking")
        self.PCA = QtWidgets.QGroupBox(self.centralwidget)
        self.PCA.setGeometry(QtCore.QRect(200, 360, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semilight")
        self.PCA.setFont(font)
        self.PCA.setObjectName("PCA")
        self.Dimension_Reduction = QtWidgets.QPushButton(self.PCA)
        self.Dimension_Reduction.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.Dimension_Reduction.setObjectName("Dimension_Reduction")
        self.MNIST = QtWidgets.QGroupBox(self.centralwidget)
        self.MNIST.setGeometry(QtCore.QRect(430, 20, 601, 241))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semilight")
        self.MNIST.setFont(font)
        self.MNIST.setObjectName("MNIST")
        self.Show_Model_Structure = QtWidgets.QPushButton(self.MNIST)
        self.Show_Model_Structure.setGeometry(QtCore.QRect(20, 30, 151, 21))
        self.Show_Model_Structure.setObjectName("Show_Model_Structure")
        self.Reset = QtWidgets.QPushButton(self.MNIST)
        self.Reset.setGeometry(QtCore.QRect(20, 150, 151, 21))
        self.Reset.setObjectName("Reset")
        self.myLabel = QLabel(self.MNIST)
        self.myLabel.setGeometry(QtCore.QRect(20, 180, 151, 21))  # X, Y, Width, Height
        self.Predict = QtWidgets.QPushButton(self.MNIST)
        self.Predict.setGeometry(QtCore.QRect(20, 110, 151, 21))
        self.Predict.setObjectName("Predict")
        self.Show_Accuracy_and_Loss = QtWidgets.QPushButton(self.MNIST)
        self.Show_Accuracy_and_Loss.setGeometry(QtCore.QRect(20, 70, 151, 21))
        self.Show_Accuracy_and_Loss.setObjectName("Show_Accuracy_and_Loss")
        # self.MNISTtext = QtWidgets.QTextEdit(self.MNIST)
        # self.MNISTtext.setGeometry(QtCore.QRect(220, 30, 351, 181))
        # self.MNISTtext.setObjectName("MNISTtext")
        self.paint_widget = PaintWidget(self.centralwidget)
        self.paint_widget.setObjectName("paint_widget")
        self.paint_widget.setGeometry(650, 30, 200, 200)  # PaintWidget 大小設定600x500
        #MainWindow.setCentralWidget(self.centralwidget)
        self.ResNet50 = QtWidgets.QGroupBox(self.centralwidget)
        self.ResNet50.setGeometry(QtCore.QRect(430, 320, 601, 261))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semilight")
        self.ResNet50.setFont(font)
        self.ResNet50.setObjectName("ResNet50")
        self.Load_Image5 = QtWidgets.QPushButton(self.ResNet50)
        self.Load_Image5.setGeometry(QtCore.QRect(20, 30, 151, 21))
        self.Load_Image5.setObjectName("Load_Image5")
        self.Show_Model_Structure5 = QtWidgets.QPushButton(self.ResNet50)
        self.Show_Model_Structure5.setGeometry(QtCore.QRect(20, 110, 151, 21))
        self.Show_Model_Structure5.setObjectName("Show_Model_Structure5")
        self.Inference = QtWidgets.QPushButton(self.ResNet50)
        self.Inference.setGeometry(QtCore.QRect(20, 190, 151, 21))
        self.Inference.setObjectName("Inference")
        self.myLabel2 = QLabel(self.ResNet50)
        self.myLabel2.setGeometry(QtCore.QRect(20, 220, 151, 21))  # X, Y, Width, Height
        self.Show_Comparison = QtWidgets.QPushButton(self.ResNet50)
        self.Show_Comparison.setGeometry(QtCore.QRect(20, 150, 151, 21))
        self.Show_Comparison.setObjectName("Show_Comparison")
        self.Show_Images = QtWidgets.QPushButton(self.ResNet50)
        self.Show_Images.setGeometry(QtCore.QRect(20, 70, 151, 21))
        self.Show_Images.setObjectName("Show_Images")
        self.ResNet50Text = QtWidgets.QTextEdit(self.ResNet50)
        self.ResNet50Text.setGeometry(QtCore.QRect(220, 30, 361, 181))
        self.ResNet50Text.setObjectName("ResNet50Text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Load_Image.setText(_translate("MainWindow", "Load Image"))
        self.Load_Video.setText(_translate("MainWindow", "Load Video"))
        self.Background_Subtraction.setTitle(_translate("MainWindow", "1.Background Subtraction"))
        self.Background_Subtraction_button.setText(_translate("MainWindow", "1. Background Subtraction"))
        self.Optical_Flow.setTitle(_translate("MainWindow", "2. Optical Flow"))
        self.Preprocessing.setText(_translate("MainWindow", "2.1 Preprocessing"))
        self.Video_tracking.setText(_translate("MainWindow", "2.2 Video tracking"))
        self.PCA.setTitle(_translate("MainWindow", "3. PCA"))
        self.Dimension_Reduction.setText(_translate("MainWindow", "3. Dimension Reduction"))
        self.MNIST.setTitle(_translate("MainWindow", "4. MNIST Classifier Using VGG19"))
        self.Show_Model_Structure.setText(_translate("MainWindow", "1. Show Model Structure"))
        self.Reset.setText(_translate("MainWindow", "4. Reset"))
        self.Predict.setText(_translate("MainWindow", "3. Predict"))
        self.Show_Accuracy_and_Loss.setText(_translate("MainWindow", "2. Show Accuracy and Loss"))
        self.ResNet50.setTitle(_translate("MainWindow", "5. ResNet50"))
        self.Load_Image5.setText(_translate("MainWindow", "Load Image"))
        self.Show_Model_Structure5.setText(_translate("MainWindow", "5.2 Show Model Structure"))
        self.Inference.setText(_translate("MainWindow", "5.4 Inference"))
        self.Show_Comparison.setText(_translate("MainWindow", "5.3 Show Comparison"))
        self.Show_Images.setText(_translate("MainWindow", "5.1 Show Images"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
